// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCuoMUwDdng1rRJ3FUzijRJwjSXBT7zUA',
    appId: '1:843945680710:android:73a3bc35b10269866c4f47',
    messagingSenderId: '843945680710',
    projectId: 'dieayap-793dd',
    storageBucket: 'dieayap-793dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvnBKfmQfoqUGZuuXXFk4JAm0iTqLJlmw',
    appId: '1:843945680710:ios:bacc49c9affb51f06c4f47',
    messagingSenderId: '843945680710',
    projectId: 'dieayap-793dd',
    storageBucket: 'dieayap-793dd.firebasestorage.app',
    iosBundleId: 'com.dieayaplus.userdev',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa2dgLmTivMPoMHECV8DqEV-yTatgc2LE',
    appId: '1:599093109994:web:736f4de54905c6d1d3a393',
    messagingSenderId: '599093109994',
    projectId: 'abd-el-rahman1',
    authDomain: 'abd-el-rahman1.firebaseapp.com',
    storageBucket: 'abd-el-rahman1.firebasestorage.app',
    measurementId: 'G-HCPNLR38BS',
  );

}