// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCuoMUwDdng1rRJ3FUzijRJwjSXBT7zUA',
    appId: '1:843945680710:android:0dc8a2157642d5066c4f47',
    messagingSenderId: '843945680710',
    projectId: 'dieayap-793dd',
    storageBucket: 'dieayap-793dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvnBKfmQfoqUGZuuXXFk4JAm0iTqLJlmw',
    appId: '1:843945680710:ios:a5045259d1e6f3fb6c4f47',
    messagingSenderId: '843945680710',
    projectId: 'dieayap-793dd',
    storageBucket: 'dieayap-793dd.firebasestorage.app',
    iosBundleId: 'com.dieayaplus.marketdev',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhRG-Uoie2bJwQja2tBUvMZwHFHUSK05A',
    appId: '1:843945680710:web:db90bf74a0963d236c4f47',
    messagingSenderId: '843945680710',
    projectId: 'dieayap-793dd',
    authDomain: 'dieayap-793dd.firebaseapp.com',
    storageBucket: 'dieayap-793dd.firebasestorage.app',
  );

}